### PR TITLE
Turned off debug mode in shared_library

### PR DESCRIPTION
**Pull request by alespergl**
This turns off the debug mode for the shared_library build configuration for the time being, as was agreed by the maintainers. There's no need to revert the "dcheck" patches, as they have no effect in non-debug mode.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@jkleinsc All the builds were aborted, can you please restart them?

**Comment by jkleinsc** [comment]
@alexeykuzmin builds have been restarted

**Comment by alexeykuzmin** [comment]
Shall we merge it? All builds are 🍏

**Comment by jkleinsc** [comment]
@alexeykuzmin Even though it was marked as green, the linux-x64 build didn't upload to S3.  I would like to test it locally with Electron on linux-x64 before merging because that the arch that we were having issues with.

**Comment by jkleinsc** [comment]
I am rerunning the linux-x64 build now, so hopefully it runs properly this time.

**Comment by alexeykuzmin** [comment]
@alespergl It seems like there is one redundant commit in this PR because of a force push into master.

**Comment by alespergl** [comment]
How did _that_ happen? Can we force-push the previous master back, so that I don't have to trigger new builds of this by rebasing?

**Comment by alexeykuzmin** [comment]
> How did *that* happen?

Bad things happen from time to time, see https://github.com/electron/libchromiumcontent/pull/336#issuecomment-321419320.

> Can we force-push the previous master back, so that I don't have to trigger new builds of this by rebasing?

I wouldn't do that, some other folks have already created PRs on the top of the new master.
Anyway, let the GitHub guys to decide.

**Comment by jkleinsc** [comment]
@alespergl it was my fault.  I'll clean it up.

**Comment by jkleinsc** [comment]
@alespergl this tests fine so I am going to merge it in.  cc @alexeykuzmin

**Pull request merged**
