### PR TITLE
Add `script/patch.py` to use during Chromium upgrades

### PR DESCRIPTION
**Pull request by alexeykuzmin**
**Motivation**:
`apply-patches` script is perfectly fine when patches could be applied without any errors,
but during upgrades to a new Chromium version it's almost useless.
`patch.py` should make work with failing patches more versatile and easier.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
Are the docstring and arguments description not enough?

```
"""
Usage: patch -h

Use this script to selectively apply and revert patches.
It is most useful during upgrades to a new Chromium version.
"""
```

$ ./patch -h
```
usage: patch [-h] [--directory DIRECTORY] [--file_path FILE_PATH] [--force]
             --repo_root REPO_ROOT [--reverse]

Apply patches to a git repo

optional arguments:
  -h, --help            show this help message and exit
  --directory DIRECTORY
                        Path to a directory with patches. If present,
                        --file_path is ignored.
  --file_path FILE_PATH
                        Path to a patch file.
  --force               Try apply all the patches even if some of them fail.
  --repo_root REPO_ROOT
                        Path to a repository root folder.
  --reverse             Reverse patches.
```

**Comment by cifratila** [comment]
@alexeykuzmin I was thinking more of adding it maybe for others here: https://github.com/electron/electron/blob/master/docs/development/upgrading-chrome.md

**Comment by alexeykuzmin** [comment]
> @alexeykuzmin I was thinking more of adding it maybe for others here: https://github.com/electron/electron/blob/master/docs/development/upgrading-chrome.md

The whole manual should be updated =/ I'm going to do that someday.
Anyway, it's in a different repo, so definitely not in this PR.

**Comment by alexeykuzmin** [comment]
Any other comments or suggestions?

**Comment by zcbenz** [comment]
👍

**Pull request merged**
