### PR TITLE
Add patch for WebmMuxer

### PR DESCRIPTION
**Pull request by demian85**
@see #253 
@see  https://codereview.chromium.org/2617143003

Thanks.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
The patch provided does not appear to apply cleanly to Chrome 53.0.2785.143

The error when running `script/update` on this branch:


```
source file is different - media/muxers/webm_muxer.cc
webm_muxer_fix.patch failed to apply
```

**Comment by demian85** [comment]
How is that possible? I specifically checked out that tag and applied patch with `git apply` and worked fine.
```
MacRamboPro:chromium-53 demian$ git log
commit 12ae4ebf489873fc4aad9efc231b9151b330a938
Author: chrome-cron <chrome-cron@google.com>
Date:   Sun Sep 25 01:36:29 2016 +0000

    Publish DEPS for Chromium 53.0.2785.143
MacRamboPro:chromium-53 demian$ git tag -l
53.0.2785.143
```

What should I do? Is that commit the correct one?

**Comment by kevinsawicki** [comment]
How is that possible? I specifically checked out that tag and applied patch with git apply and worked fine.

I think the patch library uses to apply them in `libchromiumcontent` has stricter SHA checks.

So if you apply the patch to a `53.0.2785.143` checkout using `git apply` and then run `git diff`, you'll see the updated patch.

Here is it for:


```patch
diff --git a/media/muxers/webm_muxer.cc b/media/muxers/webm_muxer.cc
index 0633baf..c134f77 100644
--- a/media/muxers/webm_muxer.cc
+++ b/media/muxers/webm_muxer.cc
@@ -234,8 +234,6 @@ void WebmMuxer::AddVideoTrack(const gfx::Size& frame_size, double frame_rate) {
   DCHECK_EQ(0ull, video_track->crop_bottom());
   DCHECK_EQ(0.0f, video_track->frame_rate());
 
-  video_track->set_default_duration(base::Time::kNanosecondsPerSecond /
-                                    frame_rate);
   // Segment's timestamps should be in milliseconds, DCHECK it. See
   // http://www.webmproject.org/docs/container/#muxer-guidelines
   DCHECK_EQ(1000000ull, segment_.GetSegmentInfo()->timecode_scale());
```

**Comment by demian85** [comment]
So, updated patch. Does it work now?

**Comment by kevinsawicki** [comment]
Thanks for this 👍

**Comment by kevinsawicki** [comment]
@demian85 this was released in Electron 1.4.15

**Pull request merged**
