### PR TITLE
[WIP] Upgrade to Chromium 60

### PR DESCRIPTION
**Pull request by alexeykuzmin**
**TODO** Change target branch to *master*.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
Can someone please trigger Linux builds?

**Comment by jkleinsc** [comment]
@alexeykuzmin builds have been triggered

**Comment by alexeykuzmin** [comment]
@zcbenz @jkleinsc 
It seems like all Jenkins builds (libcc and Electron) are hanging. I guess something is broken on the server.

**Comment by jkleinsc** [comment]
@alexeykuzmin @zcbenz I just restarted our Jenkins cluster which unfortunately killed all the builds queued, but hopefully we a good to go now.

**Comment by alexeykuzmin** [comment]
@zcbenz FYI
Chromium 60.0.3112.78 build fails with GTK2 (`use_gtk3=false`).

**Comment by alexeykuzmin** [comment]
Is there a way to restart a certain failed Jenkins build?
Both Mac builds have failed on uploading artifacts and I would prefer to restart only them instead of all the builds.

@jkleinsc, @zcbenz

**Comment by alexeykuzmin** [comment]
We are going to skip Chromium 60 and upgrade to 61 instead.
See #335. Closed.

**Comment by zcbenz** [comment]
> Is there a way to restart a certain failed Jenkins build?

It is possible but involves setting up some complex Jenkins plugin.

**Pull request closed without merging**
