### PR TITLE
Add freetype 2.8.1 patch

### LINKED ISSUE #384: Subpixel font rendering with freetype 2.8.1
With updated libfreetype fonts look "dirty" and painful to read due background artifacts. Here is a screenshot from unmodified `electron-quick-start`:

spectacle h23809

The issue affects all the Linux users with new version of the library. See: atom/atom#15737, Microsoft/vscode#35675.

It seems to be [upstream Skia issue](https://bugs.chromium.org/p/skia/issues/detail?id=6663). The fix could probably be backported from newer Chromium versions.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #384

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@alexeykuzmin When this is merged it can be deleted in the chromium 61 branch (this patch is in chromium 61+)

**Comment by alexeykuzmin** [comment]
@MarshallOfSound 👍

**Comment by alexeykuzmin** [comment]
@MarshallOfSound Should it be merged? All the checks seem to be fine.

**Comment by MarshallOfSound** [comment]
@alexeykuzmin Yeah, if someone approves all 3 PR's we can merge them in 👍

**Comment by alexeykuzmin** [comment]
@ckerr If a patch just backports something from a newer version as is,
it will simply fail when we try to apply it to that version. It actually happens almost every Chromium and Node.js upgrade.
But if a patch is a temporary workaround, I would prefer to have an open issue to remove it when it's no longer needed.

**Pull request merged**
