### PR TITLE
Enabled all debug checks

### PR DESCRIPTION
**Pull request by alespergl**
Please use builds from this branch to fix debug check violations in Electron.

This branch enables *all* debug checks including V8 and general Chromium ones, and as such presents the greatest challenge because Electron triggers those checks often.

There's another branch which enables only some debug checks whose violations should be easier to fix:
https://github.com/electron/libchromiumcontent/pull/326

**Tip:** Symbol files for libcc are stored at the same location as the published `libchromiumcontent.zip` file, only the file is named `libchromiumcontent-dbg.zip`

### CODE REVIEW

**Comment by alespergl** [comment]
Rebased on current master.

**Comment by alexeykuzmin** [comment]
@alespergl Do you still need this PR?

**Comment by deepak1556** [comment]
`Angle`, `Skia` and `v8` are the only components that have DCHECK disabled apart from the existing `002-dcheck.patch`. I think we can use https://github.com/electron/libchromiumcontent/pull/326 and close this one. Trying to fix with all of them enabled at once will be difficult.

**Comment by alespergl** [comment]
Let's leave them both open for now as a reminder that there's still work to be done. I'll rebase them on master as soon as I have a moment.

**Comment by ckerr** [comment]
@alespergl Do you still need this PR?

**Comment by alexeykuzmin** [comment]
Since there's no response from @alespergl and the libcc repo is going to be archived soon, I'm going to close this PR.

**Pull request closed without merging**
