### PR TITLE
Add patch for nvidia GPU's on High Sierra

### PR DESCRIPTION
**Pull request by MarshallOfSound**
/cc @bpasero

### CODE REVIEW

**Comment by jkleinsc** [comment]
@poiru if someone wants to patch it for 1.7, yes we can backport it there

**Comment by poiru** [comment]
@jkleinsc Happy to do it! Seems like this was reverted though?

**Comment by jkleinsc** [comment]
@poiru I was a bit aggressive in merging.  We need to test it against an Electron build before merging it in.  In talking to @MarshallOfSound and others today, this fix is an upstream quick/hacky fix from chromium canary that simply blacklists certain gpu features, so while it fixes the issue its a temporary fix at best.

**Comment by alexeykuzmin** [comment]
>  if someone wants to patch it for 1.7, yes we can backport it there

https://github.com/electron/libchromiumcontent/pull/379
@jkleinsc, @poiru

**Pull request merged**
