### PR TITLE
Use sccache with clang-cl support and new features for devs

### PR DESCRIPTION
**Pull request by MarshallOfSound**
clang-cl support: https://github.com/mozilla/sccache/pull/245
_something else?_

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@MarshallOfSound 
I added a link to https://github.com/mozilla/sccache/pull/245 to the PR description.
Can you please add links to other changes the new version brings in?

**Comment by jkleinsc** [comment]
@alexeykuzmin looks like the mas-shared job failed trying to run sccache: 
```
2018-05-16T06:13:38.7022530Z ##[section]Starting: Build
2018-05-16T06:13:38.7122190Z ==============================================================================
2018-05-16T06:13:38.7140390Z Task         : Bash
2018-05-16T06:13:38.7158830Z Description  : This is an early preview. Run a Bash script on macOS, Linux, or Windows
2018-05-16T06:13:38.7177190Z Version      : 3.127.0
2018-05-16T06:13:38.7195390Z Author       : Microsoft Corporation
2018-05-16T06:13:38.7213360Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613738)
2018-05-16T06:13:38.7231600Z ==============================================================================
2018-05-16T06:13:39.2425020Z Generating script.
2018-05-16T06:13:39.2716720Z [command]/bin/bash --noprofile --norc /Users/electron/vsts-agent/vsts-agent-osx-x64-2.131.0/_work/_temp/77041c9a-5964-4d3c-8085-8af3f62e2ec7.sh
2018-05-16T06:13:39.3610000Z Starting sccache server...
2018-05-16T06:13:44.3790320Z error: Timed out waiting for server startup
2018-05-16T06:13:47.0340280Z ##[error]Bash exited with code '2'.
2018-05-16T06:13:47.0461240Z ##[section]Finishing: Build
```

I can restart it to see if it was just a fluke

**Comment by MarshallOfSound** [comment]
@jkleinsc Urgh, looks like I didn't build with the right feature flags. Here we go again 😆

**Comment by jkleinsc** [comment]
@MarshallOfSound thanks for updating.  I now see that Azure is being used, but it looks like the Windows builds are still not using it.  From https://windows-ci.electronjs.org/project/AppVeyor/libchromiumcontent/build/1.0.1590/job/9fmwwsetxju4pps9:
```
[00:57:47] 
[00:57:47] Compile requests                 0
[00:57:47] Compile requests executed        0
[00:57:47] Cache hits                       0
[00:57:47] Cache misses                     0
[00:57:47] Cache timeouts                   0
[00:57:47] Cache read errors                0
[00:57:47] Forced recaches                  0
[00:57:47] Cache write errors               0
[00:57:47] Compilation failures             0
[00:57:47] Cache errors                     0
[00:57:47] Non-cacheable compilations       0
[00:57:47] Non-cacheable calls              0
[00:57:47] Non-compilation calls            0
[00:57:47] Unsupported compiler calls       0
[00:57:47] Average cache write          0.000 s
[00:57:47] Average cache read miss      0.000 s
[00:57:47] Average cache read hit       0.000 s
[00:57:47] Cache location             Azure, container: BlobContainer(url=https://libcc*****.blob.core.windows.net/*****/)

**Comment by alexeykuzmin** [comment]
@MarshallOfSound 
This PR seems to be quite old, do we still need it?

**Pull request closed without merging**
