### PR TITLE
Upgrade to Chromium 50.0.2661.94

### PR DESCRIPTION
**Pull request by bbondy**
- [x]  Update all the patches
- [x] Compile on OS X
- [x] Compile on Linux
- [x] Compile on Windows
- [x] Check everything works with Electron on OS X
- [x] Check everything works with Electron on Linux
- [x] Check everything works with Electron on Windows

## Changes: 

 Use Windows 10 SDK again
    base/win/win_util.cc uses #include <uiviewsettingsinterop.h> now which is required for 49.0.2623.108

Use moved components prefs
    https://codereview.chromium.org/1662523004

 Upgrade to 50.0.2661.86
   And rebase the patches

### CODE REVIEW

**Comment by bbondy** [comment]
Note also that the tarball for 50.0.2661.86 on `electron/chromium-source-tarball` also had the wrong version inside. So you have to either use the brave fork or fix the tarball for testing.

**Comment by paulcbetts** [comment]
@zcbenz If you can get this merged or otherwise built, I can start helping @bbondy on Brightray / Electron

**Comment by zcbenz** [comment]
@paulcbetts We are still working on the Windows 10 SDK problem on our CI machine, so I can not merge this for now.

**Comment by andresiraola** [comment]
@zcbenz any progress?

**Comment by bbondy** [comment]
This is ready to go.

**Comment by zcbenz** [comment]
Thanks!

**Comment by felixrieseberg** [comment]
@bbondy: You're the man. Thanks!

**Pull request merged**
