### PR TITLE
Enabled ANGLE and Skia debug checks

### PR DESCRIPTION
**Pull request by alespergl**
Please use builds from this branch to fix debug check violations in Electron.

This particular branch only enables debug checks in ANGLE and Skia libraries, so that it's possible to focus on violations specifically in those libraries.

There's another branch which enables *all* debug checks, and presents a greater challenge for fixing bugs:
https://github.com/electron/libchromiumcontent/pull/327

**Tip:** Symbol files for libcc are stored at the same location as the published `libchromiumcontent.zip` file, only the file is named `libchromiumcontent-dbg.zip`

### CODE REVIEW

**Comment by alespergl** [comment]
Note: The ANGLE/Skia dchecks are triggered by Electron's offscreen rendering tests on Windows. However, you may not be able to reproduce them locally. But offscreen rendering seems to be the offending feature.

I was able to capture this call stack on the CI system which indicates one of the bugs:
```
 Index  Function
--------------------------------------------------------------------------------
*1      ntdll.dll!ZwTerminateProcess() Line 531
 2      ntdll.dll!RtlExitUserProcess(long ExitStatus=3) Line 1370
 3      kernel32.dll!ExitProcessImplementation(unsigned int uExitCode) Line 2557
 4      ucrtbased.dll!exit_or_terminate_process(const unsigned int return_code=3) Line 130
 5      ucrtbased.dll!common_exit(const int return_code=3, const _crt_exit_cleanup_mode cleanup_mode=_crt_exit_no_cleanup, const _crt_exit_return_mode return_mode=_crt_exit_terminate_process) Line 267
 6      ucrtbased.dll!_Exit(int return_code=3) Line 289
 7      ucrtbased.dll!abort() Line 90
 8      skia.dll!sk_abort_no_print() Line 33
 9      skia.dll!SkBitmap::notifyPixelsChanged() Line 457
 10     skia.dll!SkBitmap::erase(unsigned int c=4294967295, const SkIRect & area={...}) Line 622
 11     electron.exe!atom::OffScreenOutputDevice::BeginPaint(const gfx::Rect & damage_rect) Line 67
 12     cc.dll!cc::SoftwareRenderer::BeginDrawingFrame() Line 74
 13     cc.dll!cc::DirectRenderer::DrawFrame(std::vector<std::unique_ptr<cc::RenderPass,std::default_delete<cc::RenderPass> >,std::allocator<std::unique_ptr<cc::RenderPass,std::default_delete<cc::RenderPass> > > > * render_passes_in_draw_order=0x000000b47070e158, float device_scale_factor=1.00000000, const gfx::Size & device_viewport_size) Line 280
 14     cc_surfaces.dll!cc::Display::DrawAndSwap() Line 327
 15     cc_surfaces.dll!cc::DisplayScheduler::DrawAndSwap() Line 136
 16     cc_surfaces.dll!cc::DisplayScheduler::AttemptDrawAndSwap() Line 343
 17     cc_surfaces.dll!cc::DisplayScheduler::OnBeginFrameDeadline() Line 361
 18     cc_surfaces.dll!base::internal::FunctorTraits<void (__cdecl cc::DisplayScheduler::*)(void) __ptr64,void>::Invoke<base::WeakPtr<cc::DisplayScheduler> const & __ptr64>(void(cc::DisplayScheduler::*)() method=0x000002943efb3adf, const base::WeakPtr<cc::DisplayScheduler> & receiver_ptr) Line 215
 19     cc_surfaces.dll!base::internal::InvokeHelper<1,void>::MakeItSo<void (__cdecl cc::DisplayScheduler::*const & __ptr64)(void) __ptr64,base::WeakPtr<cc::DisplayScheduler> const & __ptr64>(void(cc::DisplayScheduler::*)() & functor, const base::WeakPtr<cc::DisplayScheduler> & weak_ptr) Line 308
 20     cc_surfaces.dll!base::internal::Invoker<base::internal::BindState<void (__cdecl cc::DisplayScheduler::*)(void) __ptr64,base::WeakPtr<cc::DisplayScheduler> >,void __cdecl(void)>::RunImpl<void (__cdecl cc::DisplayScheduler::*const & __ptr64)(void) __ptr64,std::tuple<base::WeakPtr<cc::DisplayScheduler> > const & __ptr64,0>(void(cc::DisplayScheduler::*)() & functor, const std::tuple<base::WeakPtr<cc::DisplayScheduler> > & bound, base::IndexSequence<0> __formal={...}) Line 365
 21     cc_surfaces.dll!base::internal::Invoker<base::internal::BindState<void (__cdecl cc::DisplayScheduler::*)(void) __ptr64,base::WeakPtr<cc::DisplayScheduler> >,void __cdecl(void)>::Run(base::internal::BindStateBase * base=0x000002944b766c80) Line 343
 22     cc_surfaces.dll!base::internal::RunMixin<base::Callback<void __cdecl(void),1,1> >::Run() Line 86
 23     cc_surfaces.dll!base::CancelableCallback<void __cdecl(void)>::Forward() Line 111
 24     cc_surfaces.dll!base::internal::FunctorTraits<void (__cdecl base::CancelableCallback<void __cdecl(void)>::*)(void)const __ptr64,void>::Invoke<base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > const & __ptr64>(void(const base::CancelableCallback<void __cdecl(void)>::*)() method=0x000002943efb7ebe, const base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > & receiver_ptr) Line 235
 25     cc_surfaces.dll!base::internal::InvokeHelper<1,void>::MakeItSo<void (__cdecl base::CancelableCallback<void __cdecl(void)>::*const & __ptr64)(void)const __ptr64,base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > const & __ptr64>(void(const base::CancelableCallback<void __cdecl(void)>::*)() & functor, const base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > & weak_ptr) Line 308
 26     cc_surfaces.dll!base::internal::Invoker<base::internal::BindState<void (__cdecl base::CancelableCallback<void __cdecl(void)>::*)(void)const __ptr64,base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > >,void __cdecl(void)>::RunImpl<void (__cdecl base::CancelableCallback<void __cdecl(void)>::*const & __ptr64)(void)const __ptr64,std::tuple<base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > > const & __ptr64,0>(void(const base::CancelableCallback<void __cdecl(void)>::*)() & functor, const std::tuple<base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > > & bound, base::IndexSequence<0> __formal={...}) Line 365
 27     cc_surfaces.dll!base::internal::Invoker<base::internal::BindState<void (__cdecl base::CancelableCallback<void __cdecl(void)>::*)(void)const __ptr64,base::WeakPtr<base::CancelableCallback<void __cdecl(void)> > >,void __cdecl(void)>::Run(base::internal::BindStateBase * base=0x000002944b769d00) Line 343
 28     base.dll!base::internal::RunMixin<base::Callback<void __cdecl(void),0,0> >::Run() Line 68
 29     base.dll!base::debug::TaskAnnotator::RunTask(const char * queue_function=0x0000029430eebb98, base::PendingTask * pending_task=0x000000b47070ecd8) Line 61
 30     base.dll!base::MessageLoop::RunTask(base::PendingTask * pending_task=0x000000b47070ecd8) Line 424
 31     base.dll!base::MessageLoop::DeferOrRunPendingTask(base::PendingTask pending_task={...}) Line 437
 32     base.dll!base::MessageLoop::DoWork() Line 527
 33     base.dll!base::MessagePumpForUI::DoRunLoop() Line 173
 34     base.dll!base::MessagePumpWin::Run(base::MessagePump::Delegate * delegate=0x0000029447e41ec0) Line 58
 35     base.dll!base::MessageLoop::RunHandler() Line 388
 36     base.dll!base::RunLoop::Run() Line 38
 37     content.dll!content::BrowserMainLoop::MainMessageLoopRun() Line 1678
 38     content.dll!content::BrowserMainLoop::RunMainMessageLoopParts() Line 1188
 39     content.dll!content::BrowserMainRunnerImpl::Run() Line 141
 40     content.dll!content::BrowserMain(const content::MainFunctionParams & parameters={...}) Line 46
 41     content.dll!content::RunNamedProcessTypeMain(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & process_type={...}, const content::MainFunctionParams & main_function_params={...}, content::ContentMainDelegate * delegate=0x000000b47070fc30) Line 491
 42     content.dll!content::ContentMainRunnerImpl::Run() Line 836
 43     content.dll!content::ContentMain(const content::ContentMainParams & params={...}) Line 20
 44     electron.exe!wWinMain(HINSTANCE__ * instance=0x00007ff693710000, HINSTANCE__ * __formal=0x0000000000000000, wchar_t * cmd=0x000002942fcf2f24, int __formal=10) Line 184
 45     electron.exe!invoke_main() Line 118
 46     electron.exe!__scrt_common_main_seh() Line 253
 47     electron.exe!__scrt_common_main() Line 296
 48     electron.exe!wWinMainCRTStartup() Line 17
 49     kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(*)(void *) StartAddress, void * Argument) Line 64
 50     ntdll.dll!RtlUserThreadStart(long(*)(void *) StartAddress=0x0000000000000000, void * Argument=0x0000000000000000) Line 997
```

The interesting frame is
```9      skia.dll!SkBitmap::notifyPixelsChanged() Line 457```
and this is the source code for that function (from `src/third_party/skia/src/core/SkBitmap.cpp`):
```c++
void SkBitmap::notifyPixelsChanged() const {
    SkASSERT(!this->isImmutable());
    if (fPixelRef) {
        fPixelRef->notifyPixelsChanged();
    }
}
```

I had a quick look at the SkBitmap implementation and it always starts off as `isImmutable()==false`, so apparently something happens in the lifetime of that object which explicitly changes it to the immutable state.

**Comment by alespergl** [comment]
Rebased on current master.

**Comment by alexeykuzmin** [comment]
@alespergl Do you still need this PR?

**Comment by alespergl** [comment]
Well, the PR might be a bit out of date, but those DCHECKs should be enabled at some point. I'd keep it open for a little more to keep us reminded of the work that needs to be done.

**Comment by ckerr** [comment]
@alespergl Do you still need this PR?

**Comment by alexeykuzmin** [comment]
Since there's no response from @alespergl and the libcc repo is going to be archived soon, I'm going to close this PR.

**Pull request closed without merging**
