### PR TITLE
feat: Add patch for the login delegate

### PR DESCRIPTION
**Pull request by nitsakh**
Pass in the referrer and the request method arguments to fix the login handler api n electron.

### CODE REVIEW

**Comment by nornagon** [comment]
I suspect that this will be a somewhat difficult patch to maintain. The code is already different in M67. Is there any chance we could either:
a) get the information we need some other way that's less intrusive,
b) upstream this or something like it into Chromium itself, or
c) change the Electron API to not require this extra info?

**Comment by deepak1556** [comment]
> get the information we need some other way that's less intrusive,

Originally the plan was to rely on the global unique request id and extract request details based on it, but content layer doesn't provide with such utility, hence it was decided to add this patch. But upon further investigation, we could indeed achieve this on electron without the patch. Currently we setup the login delegate which is used by resource loader to handle request auth but even before the resource loader gets a chance the network layer allows network delegate to handle it but currently we deny handling it there, if we move the login handler to it we will have all the required details. I will take a stab at it tomorrow.

**Comment by nitsakh** [comment]
@deepak1556 wasn't the plan to deprecate this API and now and remove it in the next version? So that the patch will have to stay only till the next version.

**Comment by alexeykuzmin** [comment]
@nitsakh Do you still need this patch? If yes, can you please rebase it onto the latest master?

**Comment by deepak1556** [comment]
https://github.com/electron/electron/pull/14231 attempts to solve this without the patch.

**Pull request closed without merging**
