### PR TITLE
[1.8.x] [content] cherry-pick patch to allow disabling desktop capture throttling

### PR DESCRIPTION
**Pull request by alexeykuzmin**
Backports #434 to the `electron-1-8-x`.

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@CapOM I had to change the patch slightly for 1.8, but none of your code is changed, only the diff context.

**Comment by CapOM** [comment]
@alexeykuzmin Today I tried with your pull request and I confirm it works, thx a lot!

**Comment by alexeykuzmin** [comment]
@ckerr It would probably make sense to include it to the next 1.8.x release.

**Comment by CapOM** [comment]
Hello, gentle ping to merge it, thx a lot!

**Comment by alexeykuzmin** [comment]
@CapOM 
I wait for approval from @ckerr

**Pull request merged**
