### PR TITLE
Add patch for pdf support in sub frames

### PR DESCRIPTION
**Pull request by ahmedmohamedali**
This PR is a proposal to fix the issue https://github.com/electron/electron/issues/9192
The patch is fixing the following issues:

1) The  sub frame inherit the bindings from the main frame which does not have the web ui bindings.
Th fix is to reset the bindings fro the sub frame during the navigation

2) The user needs to set a name for the sub frame otherwise the web ui will be displayed in the main frame.  This limitation is removed by generating a name from the id for the sub frame when it hosts a web ui. A better approach would be to use the frame node id but this need a change in the chromium design for web ui which is based on the frame name.

3)  Messages are passed only to the web ui in the main frame. The fix is to iterate recursively the child frames and pass the message.

### CODE REVIEW

**Comment by ahmedmohamedali** [comment]
Hi @deepak1556 ,
Can you or someone from electron team start the review of this PR ? 
Thanks.

**Comment by jkleinsc** [comment]
Closing and reopening this PR to trigger CI builds

**Comment by ahmedmohamedali** [comment]
Hi electron team,

Can you please me let me know what’s the next step for this PR?

Thanks.

**Comment by deepak1556** [comment]
Hi! @ahmedmohamedali sorry for the delayed response. The changes look good to me, I am going to verify the patch this weekend. Seems like the CI failed to generate builds to test locally. Thanks!

**Comment by ahmedmohamedali** [comment]
Thanks @deepak1556  for approving this pull request.
Can you also approve the electron part #10793 ? Thanks.

**Comment by zcbenz** [comment]
The failing tests are flaky, the build is actually fine. I'm merging this with them ignored.

**Comment by zcbenz** [comment]
@alexeykuzmin A notice that this PR is adding a new patch.

**Comment by alexeykuzmin** [comment]
@zcbenz Thanks!

**Pull request merged**
